### ISSUE TITLE
Return ::placeholder rules

### ISSUE THREAD

**Issue by shrpne** [csstools/normalize.css#1]
`::placeholder` rules were [removed](https://github.com/csstools/normalize.css/commit/0dc4df63b7f6643d6dc42f65dc0129abadfbd483) due to Edge [bug](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3901363/), but it was fixed in the Edge 15

Normalize.css supports last 3 version of edge: 17, 16, 15.
 So now these rules can be returned.

**Comment by jonathantneal** [comment]
Perfect! I’ll get this re-added.
