### ISSUE TITLE
Add reasoning behind the fork to the readme

### ISSUE THREAD

**Issue by kripod** [csstools/normalize.css#13]
I've just came across the reason behind forking [necolas/normalize.css](https://github.com/necolas/normalize.css) in [the changelog of this project](https://github.com/csstools/normalize.css/blob/83a891ae47d6c2ddbb7533238c87646e2783572e/CHANGELOG.md#1000-may-16-2019):

> There are now 2 versions of normalize.css. Nicolas Gallagher and I started
> writing normalize.css together. I named and created the normalize.css
> repository with the help of Paul Irish and Ben Alman. I transferred the
> repository to Necolas, who made it into a “household” CSS library. Much
> later I resumed management of normalize.css with Luciano Battagliero. We
> tagged, deprecated, and removed “opinionated” styles — styles developers
> often prefer but which do not fix bugs or “normalize” browser differences.
> Necolas disagreed with this change, and resolved the matter AFAIK by removing
> all of the other contributors, locking discussion threads, wiping my name
> (and his) from all files, and blocking me from being able to follow the
> project.
>
> I may later create a new project with a new name, but for now I intend to
> continue working on the normalize.css project, sometimes under the
> “csstools” tag. I hope one day our differences are resolved and the projects
> will be one again.
>
> For reference within this project:
> normalize.css resolves bugs and common browser inconsistencies.
> opinionated.css does the same while preserving the classic opinionated styles.

As [discussed in a PR](https://github.com/sindresorhus/modern-normalize/pull/40#issuecomment-674510121) towards modern-normalize, this backstory should be added to the readme.

**Comment by jonathantneal** [comment]
Resolved in https://github.com/csstools/normalize.css/commit/dcf6136221ed221746ce7189531443206fa43619
