### ISSUE TITLE
Remove input { overflow: visible } as it causes inconsistencies and problems

### ISSUE THREAD

**Issue by Digital-512** [csstools/normalize.css#14]
This issue was mentioned here: [https://github.com/necolas/normalize.css/issues/779](https://github.com/necolas/normalize.css/issues/779)
And causes problems like this: [https://github.com/mozilla/send/issues/1295](https://github.com/mozilla/send/issues/1295)

Test:
1. Current result (with overflow: visible)
![](https://i.imgur.com/BaIKB83.png)

2. Expected result (without overflow: visible)
![](https://i.imgur.com/0CUvBwO.png)

Also, `<input>` element can't have child nodes in valid HTML, so it is not necessary to set overflow for it.

**Comment by jonathantneal** [comment]
Thank you for filing this. I’m trying to recreate this example, so I can better understand the problem, and then likely merge this, with an understanding of the benefits and drawbacks. Drawbacks don’t mean it’s not worth merging. It’s just about being transparent. 😄

**Comment by jonathantneal** [comment]
I’ll no longer be supporting IE.
