### ISSUE TITLE
Explain normalize.css vs opinionated.css vs evergreen.css etc

### ISSUE THREAD

**Issue by Sidewinder1138** [csstools/normalize.css#16]
I noticed there are several different css files, I was wondering if somebody could elaborate on what the differences are and when to use each of these? Thanks!!!

**Comment by pagelab** [comment]
From the [Changelog.md](https://github.com/csstools/normalize.css/blob/master/CHANGELOG.md):

- **normalize.css**: resolves bugs and common browser inconsistencies.
- **opinionated.css**: does the same while preserving the classic opinionated styles.
- **evergreen.css**: evergreen variations of normalize.css (basically, without IE support).

**Comment by jonathantneal** [comment]
Thank you, @pagelab. One other note — I’ve since removed `evergreen.css`.
