### ISSUE TITLE
Download link leads to old version

### ISSUE THREAD

**Issue by phieri** [csstools/normalize.css#23]
The project readme has a link for downloading the latest version.
https://github.com/csstools/normalize.css/blob/8e9bd2c73d7e6074bf93dbcba37188cb8e2f14a2/README.md?plain=1#L47-L49
This however does not lead to the latest version.

**Comment by romainmenke** [comment]
I've updated the hosted version for the `latest` tag and added `12.0.0`.

I've also added a script to generate all this so that it's easier to maintain going forward.
