### ISSUE TITLE
`pre` is separated from `code, kbd, samp`

### ISSUE THREAD

**Issue by pbb72** [csstools/normalize.css#24]
Commit bbcf62d separated the style rules for `pre` from `code, kbd, samp`, while being identical, and placed them under "Grouping content" without clear explanation.

Maybe I'm missing something, but this seems like an oversight and correcting it saves some bytes.

**Comment by romainmenke** [comment]
Thank you for the suggestion, I've applied this and released it in `v12.1.0`
