### ISSUE TITLE
Include `-webkit-text-size-adjust: 100%` for `html`

### ISSUE THREAD

**Issue by kripod** [csstools/normalize.css#25]
As explained by [this article](https://kilianvalkhof.com/2022/css-html/your-css-reset-needs-text-size-adjust-probably/), the following snippet normalizes text size in landscape orientation on iOS – it’s required even in the latest stable version:

```css
html {
  -webkit-text-size-adjust: 100%;
}
```

I’d suggest this snippet to be added to `normalize.css` (not just `opinionated.css`), as it makes text rendering consistent across platforms.

**Comment by romainmenke** [comment]
I agree, it is also already present in `sanitize.css` : https://github.com/csstools/sanitize.css/blob/092d0d85922bfa72d28e9e8d25d80a5437c8df44/sanitize.css#L33-L44

I've applied this and released it in `v12.1.0`
