### ISSUE TITLE
Difference between necolas/normalize.css and csstools/normalize.css

### ISSUE THREAD

**Issue by diverent2** [csstools/normalize.css#3]
Hi there :)

I´ve been planning on replacing [normalize.css](https://necolas.github.io/normalize.css/) via postcss-normalize and now found out, that your normalize.css differs in some aspects from necolas ones.
ex.` body { margin: 0 }`

Now I´m confused what the difference between the two libraries is and what to use.
Also I wonder why postcss-normalize isn´t simply using the well-established [normalize.css](https://necolas.github.io/normalize.css/)  library for your postcss-pluginas as a codebase.

Maybe you can solve my confusion :)

**Comment by jonathantneal** [comment]
I use normalize.css to fix inconsistencies between browsers in how they style elements by default. There are 3 reasons it is more helpful for me to use the csstools version:

- The necolas version includes non-fixes, previously known as opinionated defaults before such documentation was removed, like `body { margin: 0 }`.
- The csstools version is more actively maintained.
- I am blocked from submitting PRs or following any changes or discussions in the necolas version.

Nicolas and I co-created normalize.css, along with Luciano Battagliero, who painstakingly revived, documented, and reorganized the entire project. All of us poured our hearts into normalize.css.

**Comment by diverent2** [comment]
Thanks for the quick answer!
With these facts in mind I think I will go with the your postCSS solution, thank you 👍

**Comment by mrtnbroder** [comment]
You guys should add this to the readme, as I (and I think many other people) will want to know the difference between this one and necolas.

**Comment by acmilank22** [comment]
> 你们应该把它添加到自述文件中，因为我（我认为很多其他人）会想知道这个和necolas之间的区别。

+1

**Comment by donniean** [comment]
> You guys should add this to the readme, as I (and I think many other people) will want to know the difference between this one and necolas.

+1

**Comment by baba43** [comment]
Wow, this is so confusing, really. When searching "normalize.css" you find two different repositories and no clue why they co-exist. After reading some discussions I still don't understand why this repo was created under the same name.

**Comment by jonathantneal** [comment]
@baba43, I hope it is not actually making your life hard, and you just came here to complain.

Good news, most toolchains abstract normalize.css away with PostCSS.
