### ISSUE TITLE
Renaming of the project

### ISSUE THREAD

**Issue by ncoden** [csstools/normalize.css#4]
As discussed in https://github.com/zurb/foundation-sites/issues/11577, there is some confusions with the purpose of this project regarding to its name "normalize.css". If one could argue the philosophical approach of the project is still to strictly "normalize" browsers, the is associated  by the whole CSS community to the historical [necolas/normalize.css](https://github.com/necolas/normalize.css) project.

The project is currently being renamed to `csstools-normalize`, but I'm opening this issue so we can track the evolution of this and receive comments (in case someone have a better name).

See discussions in:
- https://github.com/zurb/foundation-sites/issues/11577
- https://github.com/csstools/normalize.css/issues/3

**Comment by jonathantneal** [comment]
Hi @ncoden, may this issue be closed, or are there some concerns I might have left unresolved?

**Comment by jonathantneal** [comment]
Feel free to reach out if you have any other questions. I’ll be closing this for now.
