### ISSUE TITLE
Duplicate monospace in font-family

### ISSUE THREAD

**Issue by DanielRuf** [csstools/normalize.css#5]
https://github.com/csstools/normalize.css/blob/946efd2cde37c939cbdb4bb541773e6527ee8851/normalize.css#L59
Is this some trick or just wrong?

**Comment by jonathantneal** [comment]
It’s required by most browsers to size fonts correctly. https://stackoverflow.com/questions/38781089/font-family-monospace-monospace

**Comment by DanielRuf** [comment]
Ah, thanks for the info =)
